use DB_AMS
go

CREATE TABLE TCurso (
ID int IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(60) NOT NULL
);
go

CREATE TABLE TDisciplina (
ID int IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
PERIODO INT NOT NULL,
PESO INT NOT NULL,
CURSOID INT,
FOREIGN KEY (CURSOID) REFERENCES TCurso(ID)
);
go

CREATE TABLE TAluno(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(60),
CURSOID INT,
FOREIGN KEY(CURSOID) REFERENCES TCurso(ID)
);
go

CREATE TABLE Pre_Requis(
ID_DISCIPLINA INT,
ID_PREREQUISITO INT,
FOREIGN KEY(ID_DISCIPLINA) REFERENCES TDisciplina(ID)
);
go

CREATE TABLE Aluno_Disciplina(
ID_ALUNO INT,
ID_DISCIPLINA INT)
go

CREATE TABLE Aluno_Curso(
ID_ALUNO INT,
ID_CURSO INT,
FOREIGN KEY(ID_ALUNO) REFERENCES TAluno(ID),
FOREIGN KEY(ID_CURSO) REFERENCES TCurso(ID)
);
go

CREATE TABLE Disciplina_Curso(
ID_CURSO INT,
ID_DISCIPLINA INT,
FOREIGN KEY(ID_DISCIPLINA) REFERENCES TDisciplina(ID),
FOREIGN KEY(ID_CURSO) REFERENCES TCurso(ID)
);
