insert into subject(description, semester, weight)
VALUES
('IPD'	,	1	,	4),
('CÁLCULO 1'	,	1	,	5),
('GEOMETRIA ANALÍTICA'	,	1	,	5),
('FÍSICA 1'	,	1	,	5),
('QUÍMICA X'	,	1	,	3),
('GEOMETRIA DESCRITIVA'	,	1	,	3),
('CÁLCULO NUMÉRICO'	,	2	,	4),
('CÁLCULO 2'	,	2	,	5),
('ÁLGEBRA LINEAR III'	,	2	,	5),
('FÍSICA 2'	,	2	,	5),
('QUIMICA XI'	,	2	,	3),
('DESENHO BÁSICO'	,	2	,	3),
('PROBEST'	,	3	,	5),
('CÁLCULO 3'	,	3	,	5),
('ANÁLISE VETORIAL'	,	3	,	4),
('FÍSICA 3'	,	3	,	6),
('MECTEC'	,	3	,	4),
('DESENHO TÉCNICO'	,	3	,	3),
('ENGENHARIA NA SOCIEDADE'	,	4	,	2),
('ELETRICIDADE II'	,	4	,	3),
('FÍSICA IV'	,	4	,	6),
('RESMAT'	,	4	,	3),
('FETRANS'	,	4	,	3),
('ELETRÔNICA I'	,	5	,	4),
('CIRCUITOS I'	,	5	,	4),
('ELETRÔNICA II'	,	6	,	4),
('ELETROMAGNETISMO'	,	5	,	4),
('CEME III'	,	5	,	4),
('ALGORITMOS'	,	5	,	4),
('MODELOS'	,	5	,	4),
('MATERIAIS'	,	6	,	3),
('ESTRUTURAS DE INFORMAÇÃO'	,	6	,	3),
('TECDIG 1'	,	6	,	4),
('CIRCUITOS 4'	,	6	,	4),
('ASF'	,	6	,	4),
('SHT'	,	6	,	2),
('ADM'	,	7	,	3),
('ANÁLISE DE ALGORITMOS'	,	7	,	3),
('TECDIG 2'	,	7	,	4),
('FUNDAMENTOS DOS COMP. DIGITAIS'	,	7	,	4),
('INST. AMB. COMPUTACIONAL'	,	7	,	3),
('PRINC. DE TELECOM'	,	7	,	4),
('CONTROLE E SERVOMEC'	,	7	,	4),
('CARAC. DAS LINGUAGENS DE PROG'	,	8	,	3)	,
('LAB PROG 1'	,	8	,	3)	,
('ARQ. COMPUTADORES 1'	,	8	,	4)	,
('MICRO E MICRO'	,	8	,	4)	,
('ENG. DE SISTEMAS A'	,	8	,	3)	,
('INTRO. ECONOMIA'	,	8	,	4)	,
('TEORIA DOS COMPILADORES'	,	9	,	4)	,
('PROJ. DE GRADUAÇÃO XI-A'	,	9	,	2)	,
('ARQ. SO'	,	9	,	3)	,
('TELEPROC. E REDES'	,	9	,	4)	,
('ENG. DE SISTEMAS B'	,	9	,	3)	,
('PROJ. DE AMBIENTE COMPUTACIONAL'	,	9	,	2)	,
('ESTÁGIO SUPERVISIONADO XI-A'	,	9	,	1)	,
('TÓPICOS EM ENG. SIST 1'	,	10	,	3)	,
('PROJ. GRADUAÇÃO XI-B'	,	10	,	2)	,
('CONTROLE DE PROC. POR COMPUTADOR'	,	10	,	4)	,
('TÓPICOS EM ENG. SIST 2'	,	10	,	3)	,
('ENG. DE SISTEMAS C'	,	10	,	3)	,
('ENG. NA SOCIEDADE'	,	10	,	2);